home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('halaman2/', views.halaman2, name='halaman2'),
]

story1applied/urls.py
from django.urls import path

from . import views

app_name = 'story1applied'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1applied/', include('story1applied.urls'))
]

home/models.py
from django.db import models

# Create your models here.

story1applied/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

def halaman2(request):
    return render(request, 'home/halaman2.html')

story1applied/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'story1applied/index.html')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home/styles.css' %}">
        <script src="https://kit.fontawesome.com/yourcode.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>NomadLyfe</title>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-main sticky-top">
            <div class="container">
                <div class="row">
                    <img class="image-circle pfp" src="{% static 'images/profile.jpg' %}" alt="profile pic" style="padding-top: 2%; object-fit:cover; object-position: 0 0px;">
                    <a class="navbar-brand" href="#">   
                        <h2 class="tulisan">Nomad Jeff</h2>
                        <p class="tulisan">Steam ID: nomadWarrior13</p>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav mr-auto">
                                <a class="nav-item active" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
                                <a class="nav-item " href="{% url 'home:index' %}#about">About</a>
                                <a class="nav-item " href="{% url 'home:index' %}#container3">Experiences</a>
                                <a class="nav-item " href="{% url 'home:index' %}#contacter">Contact</a>
                                <a class="nav-item " href="{% url 'home:halaman2' %}">Favorite Movie</a>
                                <a class="nav-item " href="{% url 'story1applied:index' %}">Story 1</a>
                            </div>
                        </div>
                    </a>
                </div>
            
            </div>
        </nav>

        {% block content %}
        {% endblock %}
    </body>
</html>

home/templates/home/halaman2.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid bg-main2 h-with-nav">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/tenki-no-ko-episode-1">
                        <img src="{% static 'images/tenkinoko.jpg' %}" alt="tenki no ko" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/kimi-no-na-wa-episode-1">
                        <img src="{% static 'images/kiminonawa.jpg' %}" alt="kimi no nawa" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
            <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" >
                    <a class="center" href="https://gogoanime.so/koe-no-katachi-movie-episode-1">
                        <img src="{% static 'images/koenokatachi.jpeg' %}" alt="koe no katachi" style="height: 360px; width: 260px;" style="margin: ;">
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<div id="container2">
    <div class="col-lg-13" style="padding: 7%;" style="background-color: white;">
        <table class="table table-striped">
            <tr>
                <th>Interests</th>
                <th>Details</th>
                <th>Goals</th>
            </tr>
            <tr>
                <td>Linguistic</td>
                <td>I like learning new languages</td>
                <td>To learn 10 languages</td>
            </tr>
            <tr>
                <td>History</td>
                <td>I love mesopotamian history</td>
                <td>Finding out </td>
            </tr>
            <tr>
                <td>Politics</td>
                <td>I like hammurabbi's tactics and policies</td>
                <td>Able to read hammurabbi's codex</td>
            </tr>
            <tr>
                <td>Geography</td>
                <td>Learning about middle eastern terrain</td>
                <td>Learn more about iraqi climate</td>
            </tr>
            <tr>
                <td>Data Science</td>
                <td>I'm currently planning on learning data science</td>
                <td>Able to create my first AI</td>
            </tr>
            <tr>
                <td>WebDev</td>
                <td>Currently studying bootstrap</td>
                <td>Able to make my own website</td>
            </tr>
        </table>
    </div>
</div>


<div id="about">
    <div class="col" style="padding-left: 10%; padding-top: 2%; padding-bottom: 8%; background-color:rgb(59, 58, 58)">
        <div id="headinge">
            <h3 style="color: aliceblue;">About Me</h3>
        </div>
        <div class="container-fluid bg-main2 h-with-nav">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/bahasa.jpg' %}">
                            <h3 class="text-dark">Language Nerd</h3>
                            <h4 class="text-dark">
                                I like to learn new<br>languages.<br>I currently speak 5<br>fluently and planning to <br> learn more in the future
                            </h4>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/francome.jpg' %}" style="height: -110%;">
                            <h3 class="text-dark">Biography</h3>
                            <h4 class="text-dark">
                                I am a student at <br>the University of Indonesia <br>Name : Nomad Jeff <br>Faculty : Computer Science <br>ID : 1906652000
                            </h4>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12 p-2 d-flex align-items-center justify-content-center">
                        <div class="about-box bg-main3 border-main4 p-2 text-center d-flex justify-content-center align-items-center flex-column" style="background-color: aliceblue;">
                            <img class="img-thumbnail" src="{% static 'images/french.png' %}">
                            <h3 class="text-dark">Je Parle Français</h3>
                            <h4 class="text-dark">
                                Je suis Francophone mais <br>pas de la terre <br>francophone.<br> J'ai appris la langue<br>pour 5 mois seulement
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>


<div id="container3">
    <div class="col-lg-13" style="padding: 7%;" style="background-color: white;">
        <div id="headinge">
            <h3 style="color: aliceblue;">Experiences</h3>
        </div>
        
        <table class="table table-striped" style="background-color: aliceblue;">
            <tr>
                <th><h3>Portofolio</h3></th>
            </tr>
            <tr>
                <td>* Gold Medal, Computer Science competition in Asgardia</td>
            </tr>
            <tr>
                <td>* Nobel Award, The discovery of Dormammu's black dimention</td>
            </tr>
            <tr>
                <td>* The President of Nengushite Republic for 2 periods</td>
            </tr>
            <tr>
                <td>* WWE Championship, heavy weight championship</td>
            </tr>
            <tr>
                <td>* Invention, The invention of the two-headed stalagmite dragon</td>
            </tr>
            <tr>
                <td>* World's first professor to create 10.000 useless inventions</td>
            </tr>
        </table>
    </div>
</div>

<div id="contacter">
    <div id="contact-message">
        <h1> Me Contacter s'il vous plait<br>--------<>--------</h1>
    </div>
    <div class="social">
        <a href="https://gitlab.com/matthewsolomon_"><i class="fa fa-gitlab"></i></a>
        <a href="https://www.linkedin.com/mwlite/in/matthew-tumbur-parluhutan-solomon-siregar-55477b1ab"><i class="fa fa-linkedin"></i></a>
        <a href="https://www.instagram.com/matthewsolomon_/?hl=en"><i class="fa fa-instagram"></i></a>
        <a href="https://steamcommunity.com/id/mattvdb3/"><i class="fa fa-steam"></i></a>
    </div>
</div>
{% endblock %}

story1applied/templates/story1applied/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

    <head>
        <link rel="shortcut icon" type="image/png" href="https://listimg.pinclipart.com/picdir/s/519-5198165_pepehands-png-clipart.png">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'story1applied/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Matthew T.P. Solomon</title>
        <style>
            
            .fa {
                padding: 20px;
                font-size: 30px;
                width: 50px;
                text-align: center;
                text-decoration: none;
              }
              
        </style>
    </head>
    <body>
        <div class="center">
            <nav class="navbar navbar-expand-lg navbar-dark bg-main sticky-top">
                <div class="container">
                    <div class="row">
                        <a class="navbar-brand" href="#">   
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav mb-auto">
                                    <a class="nav-item active" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
                                    <a class="nav-item " href="{% url 'home:index' %}#about">About</a>
                                    <a class="nav-item " href="{% url 'home:index' %}#container3">Experiences</a>
                                    <a class="nav-item " href="{% url 'home:index' %}#contacter">Contact</a>
                                    <a class="nav-item " href="{% url 'home:halaman2' %}">Favorite Movie</a>
                                    <a class="nav-item " href="#">Story 1</a>
                                </div>
                            </div>
                        </a>
                    </div>
                
                </div>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

story1applied/templates/story1applied/index.html
{% extends 'story1applied/base.html' %}
{% load static %}
{% block content %}
<div class="avatar">
    <img src="https://instagram.fcgk23-1.fna.fbcdn.net/v/t51.2885-19/s320x320/120001061_126666902188771_1503669047854425620_n.jpg?_nc_ht=instagram.fcgk23-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=kQCOmgTn6WYAX-_hiW5&oh=99f1519b13a135c89dca6c8df626cd14&oe=5F93950E" alt="No pic">
</div>
<div class="content">
    <h1>Matthew T.P. Solomon</h1>
    <h3>Fakultas Ilmu Komputer UI</h3>
    <p> NPM : 1906308500<br>
        Hobi : linguistic, alin, sejarah mesopotamia<br>
        Angkatan : 2019<br>
        Tempat, Tanggal Lahir : Jakarta, 30 Oktober 2001<br>
        Ayah : E. Siregar<br>
        Ibu : A.R. Theresia<br>
        Institusi : Universitas Indonesia
    </p>
</div>
<div class="content">
    <h4>----------------<>----------------</h4>
    <h4>Riwayat Pendidikan</h4>
    <table>
        <thead>
            <tr>
                <th>Pendidikan</th>
                <th>Nama Institusi</th>
                <th>Rentang waktu</th>
                <th>Daerah</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Perkuliahan Jurusan Ilmu Komputer</th>
                <th>Universitas Indonesia</th>
                <th>2019 - Sekarang</th>
                <th>Depok/Jakarta Selatan</th>
            </tr>
            <tr>
                <th>Sekolah Menengah Atas</th>
                <th>SMAN 81 Jakarta</th>
                <th>2016 - 2019</th>
                <th>Jakarta Timur</th>
            </tr>
            <tr>
                <th>Sekolah Menengah Pertama</th>
                <th>SMPK 5 Penabur</th>
                <th>2013 - 2016</th>
                <th>Jakarta Timur</th>
            </tr>
            <tr>
                <th>Sekolah Dasar</th>
                <th>SDK 4 Penabur</th>
                <th>2010 - 2016</th>
                <th>Jakarta Timur</th>
            </tr>
        </tbody>
    </table>
</div>
<div class="content">
    <h5>Contact Me</h5>
</div>
<div class="social">
    <a href="https://gitlab.com/matthewsolomon_"><i class="fa fa-gitlab"></i></a>
    <a href="https://www.linkedin.com/mwlite/in/matthew-tumbur-parluhutan-solomon-siregar-55477b1ab"><i class="fa fa-linkedin"></i></a>
    <a href="https://www.instagram.com/matthewsolomon_/?hl=en"><i class="fa fa-instagram"></i></a>
</div>
<div style="margin-top: 140px;">
    <h2>Je suis content que vous êtes venu dans mon site-internet. Je vous remercie</h2>
</div>
{% endblock %}